version: '3.1'
services:

  stats-db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=StatDB
      - POSTGRES_USER=StatDeveloper
      - POSTGRES_PASSWORD=StatDeveloper

  stats-server:
    build: stat/stat-server/
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STAT_SERVICE_PORT=9090
      - POSTGRES_USER=StatDeveloper
      - POSTGRES_PASSWORD=StatDeveloper
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=StatDB

  ewm-db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=ewmDB
      - POSTGRES_USER=ewmDeveloper
      - POSTGRES_PASSWORD=ewmDeveloper

  ewm-service:
    build: ewm-service/
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - EWM_SERVICE_PORT=8080
      - POSTGRES_USER=ewmDeveloper
      - POSTGRES_PASSWORD=ewmDeveloper
      - DB_NAME=ewmDB
      - DB_PORT=5432
      - DB_HOST=ewm-db
      - STAT_SERVER_HOST=stats-server
      - STAT_SERVER_PORT=9090