version: '3.1'
services:

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=StatDB
      - POSTGRES_USER=StatDeveloper
      - POSTGRES_PASSWORD=StatDeveloper

  stats-server:
    build: stat/stat-server/
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - STAT_SERVICE_PORT=9090
      - POSTGRES_USER=StatDeveloper
      - POSTGRES_PASSWORD=StatDeveloper
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=StatDB

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
