DROP TABLE IF EXISTS hits;

CREATE TABLE hits (
    hit_id int GENERATED BY DEFAULT AS IDENTITY,
    app varchar(50) NOT NULL,
    uri varchar(50) NOT NULL,
    ip varchar(50) NOT NULL,
    hit_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pkey_hit PRIMARY KEY(hit_id)
);