DROP TABLE IF EXISTS hits;

CREATE TABLE hits (
    hit_id int GENERATED BY DEFAULT AS IDENTITY,
    app varchar(50) NOT NULL,
    uri varchar(50) NOT NULL,
    ip varchar(50) NOT NULL,
    hit_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pkey_hit PRIMARY KEY(hit_id)
);

INSERT INTO hits(hit_id, app, uri, ip, hit_timestamp)
VALUES (1, 'some.app', '/hello-world', '9.10.10.10', '2020-01-01 10:00:00'),
       (2, 'some.app', '/goodbye-world', '10.10.10.10', '2020-01-01 11:00:00'),
       (3, 'some.app', '/hello-world', '9.10.10.10', '2020-01-01 12:00:00'),
       (4, 'some.app', '/goodbye-world', '10.10.10.10', '2020-01-01 13:00:00'),
       (5, 'another.app', '/hello-world', '9.10.10.10', '2020-01-01 14:00:00');